publish_to: none
name: dart_minerva
description: Minerva application.
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  minerva: ^0.2.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  dio: ^4.0.6
